# modified from: https://github.com/akshat2602/django-nextjs-boilerplate/blob/master/docker-compose.dev.yml

services:
  server:
    platform: linux/x86_64
    container_name: server
    build: ./server
    working_dir: /src
    ports:
      - "8000:8000"
    volumes:
      - ./server:/src
      - ./tmp:/tmp  # To map the /tmp directory in the container to the ./tmp directory on host (to test generating the tests.py file for now)
    env_file:
      - .env.dev
    command: >
      sh -c "python manage.py makemigrations && 
             python manage.py migrate &&
             python manage.py shell < scripts/create_superuser.py &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  client:
    container_name: client
    build: ./client
    working_dir: /src
    ports:
      - "3000:3000"
    volumes:
      - ./client:/src
      - /src/node_modules
      - /src/.next
    env_file:
      - .env.dev
    depends_on:
      - server
      - db

  db:
    container_name: db
    image: postgres:16.4
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env.dev