import Link from 'next/link';
import localFont from "next/font/local";
import './globals.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "TeachTech Toolkit",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="navbar">
          <div className="navbar-content">
            <Link href="/" className="logo-link">
              <img src="/images/custom-logo.png" alt="Logo" className="logo" />
            </Link>
            <Link href="/autograder" className="navbar-link">Gradescope Autograder</Link>
          </div>
        </header>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
