import Link from 'next/link';
import localFont from "next/font/local";
import Head from 'next/head';
import './globals.css';

export const metadata = {
  title: "TeachTech Toolkit",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
      </Head>
      <body>
        <header className="navbar">
          <div className="navbar-content">
            <Link href="/" className="logo-link">
              <img src="/images/custom-logo.png" alt="Logo" className="logo" />
            </Link>
            <Link href="/autograder" className="navbar-link" id="gradescope-link">Gradescope Autograder</Link>
          </div>
        </header>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
